### ISSUE TITLE
/usr/local/include/cmocka.h:2064:1: error: unknown type name ‘uintmax_t

### ISSUE THREAD

**Issue by itercheng** [clibs/cmocka#18]
Dear cmocka expert:
because some tools depend on "cmocka" dependency in my environment,  After installing cmocka tool, when i try to compile my build again, the error is shown  as title.  Could you help me solving this issue?  thank you in advance.

**Comment by jwerle** [comment]
Have you included `<stdint.h>` in your project?

**Comment by itercheng** [comment]
okay. Thank you for quick reply.  the reason is that this head file was  commented in /usr/local/include/cmocka.h. it can work well till they are opened. Thank you very much

vim /usr/local/include/cmocka.h 
/**
  42  * @defgroup cmocka The CMocka API
  43  *
  44  * These headers or their equivalents MUST be included prior to including
  45  * this header file.
  46  * @code
  47  * #include <stdarg.h>
  48  * #include <stddef.h>
  49  * #include <stdint.h>
  50  * #include <setjmp.h>
  51  * #include <stdint.h>
  52  * @endcode
  53  *
  54  * This allows test applications to use custom definitions of C standard
  55  * library functions and types.
  56  *
  57  * @{
