### ISSUE TITLE
The input parameter types of the function are inconsistent 

### ISSUE THREAD

**Issue by linuru** [clibs/cmocka#22]
When I visit the web url www.cmocka.org,  I found the supported parameter types of function assert_int_equal are integers.
so I thought what if I want to compare two long integer datas. 
I looked into the cmocka source code  and found that actually function assert_int_equal supports LargestIntegralType which covers long integer.
so I suggest to use 
void assert_int_equal (LargestIntegralType a, LargestIntegralType b) instead of void assert_int_equal (int a, int b)  during introduce assert macros api on website www.cmocka.org to tell user what we exactly support?

**Comment by diasbruno** [comment]
@linuru This repository is mirror only to provide [clib.json](https://github.com/clibs/cmocka/blob/master/clib.json). The development repository is on [gitlab cmocka](https://gitlab.com/cmocka/cmocka).
