### ISSUE TITLE
Coverity reports possible dereferencing of null pointer

### ISSUE THREAD

**Issue by rossmacgregor** [clibs/cmocka#4]
Coverity is reporting possible dereferencing of null pointer in _function_called. The variable expected_call is dereferenced although it appears that it may be NULL.

[Coverity error reader_ _libs_test_cmocka_cmocka-src_src_cmocka.c.html.zip](https://github.com/clibs/cmocka/files/856651/Coverity.error.reader_._libs_test_cmocka_cmocka-src_src_cmocka.c.html.zip)

**Comment by diasbruno** [comment]
I'd recommend to go to the [upstream repository](https://gitlab.com/cmocka/cmocka) for more information.
