### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by betsyrosemanuel** [clibs/cmocka#6]
hi,

   when i tried to build the cmocka library i got the following error message 
make -DCMAKE_INSTALL_PREFIX=/home/mkarthig/repo/mkarthig/5601/sw/y/build/netconfdevel/ -DCMAKE_BUILD_TYPE=Debug -DUNIT_TESTING=ON ..
-- Check if the system is big endian
-- Searching 16 bit integer
CMake Error at /usr/local/share/cmake-3.7/Modules/TestBigEndian.cmake:41 (message):
  no suitable type found
Call Stack (most recent call first):
  ConfigureChecks.cmake:142 (test_big_endian)
  CMakeLists.txt:43 (include)

-- Configuring incomplete, errors occurred!
See also "/home/mkarthig/repo/mkarthig/5601/sw/y/build/netconfdevel/cmocka-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/mkarthig/repo/mkarthig/5601/sw/y/build/netconfdevel/cmocka-master/build/CMakeFiles/CMakeError.log".

**Comment by vipyne** [comment]
hi,
can you post the logs from
`/home/mkarthig/repo/mkarthig/5601/sw/y/build/netconfdevel/cmocka-master/build/CMakeFiles/CMakeOutput.log` 
and
`/home/mkarthig/repo/mkarthig/5601/sw/y/build/netconfdevel/cmocka-master/build/CMakeFiles/CMakeError.log`
to get more information on the issue?

**Comment by diasbruno** [comment]
I'd recommend to move this to the [upstream repository](https://gitlab.com/cmocka/cmocka) for more information. But questions are always welcome.
