### ISSUE TITLE
Compilation broken under Ubuntu 16.04

### ISSUE THREAD

**Issue by aicastell** [clibs/cmocka#9]
Compiling on Ubuntu 16.04 following these steps:

    $ git clone https://github.com/clibs/cmocka.git
    $ mkdir -p cmocka/build
    $ cd cmocka/build
    $ cmake ../
    $ make

The compilation is broken with a bunch of errors like this:

    error: ISO C does not support ‘__FUNCTION__’ predefined identifier [-Wpedantic]

This repo is outdated for 3 years... Is this the proper cmoka repository?

**Comment by DEVoytas** [comment]
Nah...
See the very beginning of README:

> Mirror of git://git.cryptomilk.org/projects/cmocka.git

so go to: https://cmocka.org/ or https://git.cryptomilk.org/projects/cmocka.git/

**Comment by wdlkmpx** [comment]
This mirror needs updating

**Comment by diasbruno** [comment]
This is a fork of cmocka. I'd recommend to go to the [upstream repository](https://gitlab.com/cmocka/cmocka) for more information.
